# Generated by Django 2.2.3 on 2019-09-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='number',
            new_name='I_number',
        ),
        migrations.AddField(
            model_name='picture',
            name='S_number',
            field=models.IntegerField(default=0),
        ),
    ]
